### ISSUE TITLE
GZIP issue

### ISSUE THREAD

**Issue by dumbledore** [dumbledore/AlbiteREADER#40]
Strange bug:

Fetchig compressed data (chap06.txt)
java.io.IOException: Corrupt GZIP trailer
        at com.tinyline.util.GZIPInputStream.char(), bci=145
        at com.tinyline.util.GZIPInputStream.read(), bci=36
        at com.tinyline.util.GZIPInputStream.read(), bci=7
        at com.sun.cldc.i18n.j2me.UTF_8_Reader.getByteOfCurrentChar(), bci=41
        at com.sun.cldc.i18n.j2me.UTF_8_Reader.read(), bci=72
        at java.io.InputStreamReader.read(), bci=53
        at java.io.Reader.read(Reader.java:123)
        at org.albite.util.archive.ArchivedFile.getFileContentsAsChars(), bci=16
        at org.albite.book.model.Chapter.getTextBuffer(Chapter.java:66)
        at org.albite.book.view.Booklet.<init>(Booklet.java:52)
        at org.albite.albite.BookCanvas.reflowPages(BookCanvas.java:758)
        at org.albite.albite.BookCanvas.loadChapter(BookCanvas.java:711)
        at org.albite.albite.BookCanvas.goToFirstPage(BookCanvas.java:719)
        at org.albite.albite.BookCanvas.scrollPages(BookCanvas.java:637)
        at org.albite.albite.ScrollingTimerTask.run(ScrollingTimerTask.java:63)
        at java.util.TimerThread.mainLoop(), bci=237
        at java.util.TimerThread.run(Timer.java:462)
Memory statistics after loading chapter `Chapter 6`

**Comment by dumbledore** [comment]
Occurs in Netbeans only. For now at least.

**Comment by dumbledore** [comment]
Not troubling me for now. We may think about it again at some point...

**Comment by dumbledore** [comment]
It seems that the problem occurred because of illegal usage of `InputStream.available()`
